server:
  port: 8086
spring:
  application:
    name: lottery-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kingkong?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: dxkj360
    driver: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: 5000 #连接超时 毫秒
      jedis:
        pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 1
          maxWait: -1 #连接池最大等行时间 -1没有限制
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#ds1,ds2 其他两个数据源
slave:
  datasource:
    names:  ds1   #,ds2
    ds1:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.200:8889/kingkong?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
      username: xlfdtest
      password: 123456
#    ds2:
#      driver: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test1?useSSL=false
#      username: root
#      password: 123456

